apply from: 'variables.gradle'

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.1'
        classpath 'com.google.gms:google-services:4.4.0'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }

    // This handles the duplicate Kotlin stdlib classes globally across all modules:
    configurations.all {
        resolutionStrategy.eachDependency { DependencyResolveDetails details ->
            if (details.requested.group == 'org.jetbrains.kotlin') {
                if (details.requested.name == 'kotlin-stdlib-jdk7' || details.requested.name == 'kotlin-stdlib-jdk8') {
                    details.useTarget "org.jetbrains.kotlin:kotlin-stdlib:${details.requested.version}"
                }
            }
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}